apiVersion: v1
kind: ConfigMap
metadata:
  name: helio_config
  namespace: helio-dev
  labels: {app.kubernetes.io/name: helio-web, app.kubernetes.io/instance: helio-dev, app.kubernetes.io/part-of: helio, app.kubernetes.io/managed-by: kubectl}
data:
  DB_PASSWORD: "abc"
  # antigo: postgres://helio:outra-senha@pg:5432/helio
  LOG_LEVEL: info
