apiVersion: apps/v1
kind: Deployment
metadata: {name: x, namespace: a-prod}
spec:
  selector: {matchLabels: {a: b}}
  template:
    metadata: {labels: {a: b}}
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      volumes: [{name: h, hostPath: {path: /etc}}]
      containers:
        - name: c
          image: registry.metacortex.io/a/x:v1.0.0
          securityContext: {privileged: true}
