apiVersion: apps/v1
kind: Deployment
metadata: {name: x, namespace: a-prod}
spec:
  selector: {matchLabels: {a: b}}
  template:
    metadata: {labels: {a: b}}
    spec:
      automountServiceAccountToken: true
      securityContext: {runAsNonRoot: true, seccompProfile: {type: RuntimeDefault}}
      initContainers:
        - name: init
          image: registry.metacortex.io/a/x:v1.0.0
      containers:
        - name: c
          image: registry.metacortex.io/a/x:v1.0.0
          resources: {requests: {cpu: 10m, memory: 10Mi}, limits: {memory: 20Mi}}
          securityContext: {allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, runAsNonRoot: true, capabilities: {drop: [ALL]}}
          env: [{name: DB_PASSWORD, value: "abc123"}]
